{% set name = "geohash2" %}
{% set version = "1.1" %}
{% set sha256 = "0ed0583b1f4fc329f96d807c9a4cd895c7eed2c35479ac7b4a50725249997bda" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - geohash2


about:
  home: https://github.com/dbarthe/geohash/
  license: GPL-3.0
  license_file: LICENSE.txt
  license_family: GPL
  summary: 'Decoding and encoding Geohashes to and from latitude and longitude coordinates supporting python 3'

  description: |
   Geohash2 is a Python module that provides functions for decoding and encoding Geohashes to and from latitude and longitude coordinates. This module is a fork of https://github.com/vinsci/geohash which does not support python3
  doc_url: https://github.com/dbarthe/geohash/
  dev_url: https://github.com/dbarthe/geohash/

extra:
  recipe-maintainers:
    - david-gang
